"""The exapump glibc shim: the release binary needs glibc 2.38+, older distros run it inside a container instead.

Ported from the shell kit. The wrapper is transparent to every caller: the
same path, the same CLI; files under $HOME, /tmp and the directory the
command runs from stay visible (that last mount is the one that matters on
servers, where data lives under /srv or /data).
"""

from __future__ import annotations

import shutil

from exakit.adapters.fs.atomic import atomic_write_text
from exakit.domain.errors import Failed

SHIM = """#!/bin/sh
# exapump glibc shim - generated by the Exasol Personal Local Starter Kit.
# The exapump release binary requires a newer glibc than this system has, so
# it runs inside a container with host networking. The real binary lives at
# the path baked in below; exakit update exapump regenerates this wrapper.
if [ -t 0 ] && [ -t 1 ]; then _exakit_tty="-it"; else _exakit_tty="-i"; fi
_exakit_v=""; _exakit_vp=""
case "$PWD" in
    "$HOME"*|/tmp*) _exakit_wd="$PWD" ;;
    *)
        if [ -d "$PWD" ]; then
            _exakit_wd="$PWD"; _exakit_v="-v"; _exakit_vp="$PWD:$PWD"
        else
            echo "exapump: the current directory does not exist; relative paths will resolve against $HOME" >&2
            _exakit_wd="$HOME"
        fi ;;
esac
exec "{runtime}" run --rm $_exakit_tty --network host --userns=keep-id \\
    -u "$(id -u):$(id -g)" -e HOME="$HOME" -v "$HOME:$HOME" -v /tmp:/tmp \\
    ${{_exakit_v:+"$_exakit_v"}} ${{_exakit_vp:+"$_exakit_vp"}} -w "$_exakit_wd" \\
    "{image}" "{real}" "$@"
"""


def install_glibc_shim(lifecycle, failure_text: str) -> None:
    """Move the real binary aside, pull the image, write the wrapper at the binary's path, prove it runs."""
    ctx = lifecycle.ctx
    runtime = ctx.runner.which("podman")
    glibc = ctx.runner.run(["ldd", "--version"], timeout=10)
    have = (glibc.out.splitlines() or ["unknown glibc"])[0] if glibc.ok else "unknown glibc"
    ctx.ui.warn(f"The exapump release binary needs a newer glibc than this system provides ({have}).")
    if not runtime:
        raise Failed("exapump cannot run on this system's glibc and Podman is not available to shim it. Install Podman and re-run, "
                     "or use a distro with glibc 2.38+ (e.g. Ubuntu 24.04).", remedy="exakit update exapump")
    image = ctx.env.get("EXAKIT_EXAPUMP_SHIM_IMAGE") or ctx.catalog.kit.exapump_shim_image
    ctx.ui.info(f"Self-repair: running exapump inside a {image} container via {runtime}")
    real = ctx.paths.home / "libexec" / "exapump-real"
    real.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(lifecycle.bin), str(real))
    real.chmod(0o755)
    pulled = ctx.runner.run([runtime, "pull", image], timeout=900)
    if not pulled.ok:
        ctx.log.line("ERR", f"podman pull {image} failed: {(pulled.err or pulled.out).strip()[-300:]}")
        raise Failed(f"Could not pull {image} with {runtime}. Check network access and re-run.", remedy="exakit update exapump")
    atomic_write_text(lifecycle.bin, SHIM.format(runtime=runtime, image=image, real=real), mode=0o755)
    check = ctx.runner.run([str(lifecycle.bin), "--version"], timeout=120)
    if not check.ok:
        raise Failed(f"exapump still does not run through the {image} container: {(check.err or check.out).strip()[-200:] or failure_text[:200]}",
                     remedy="exakit logs setup")
    lifecycle.record(shim_image=image, real_binary=str(real))
    ctx.ui.ok(f"exapump runs through the {image} container (the real binary is at {real})")
