"""A prebuilt binary from a GitHub release: download, verify, place under tools/<id>/, launcher in the bin dir."""

from __future__ import annotations

from pathlib import Path

from exakit.domain.errors import Failed

from . import releases
from .base import LifecycleBase, make_executable, temp_dir


class BinaryLifecycle(LifecycleBase):
    @property
    def home(self) -> Path:
        """The add-on's folder under the kit home."""
        return self.ctx.paths.home / self.addon.id

    @property
    def engine(self) -> Path:
        """The prebuilt binary under libexec."""
        exe = ".exe" if self.ctx.platform.os == "windows" else ""
        return self.home / "libexec" / f"{self.addon.id.replace('-', '_')}{exe}"

    def asset_name(self, version: str) -> str | None:
        """The release asset for this platform on the first site that publishes one; None where none does."""
        return releases.asset_for(self, version, self.ctx.platform.platform_key)

    def digest_key(self, version: str) -> str:
        """The platform's key in versions.json's digests."""
        keys = self.addon.source.get("digest_keys") or {}
        return str(keys.get(self.ctx.platform.platform_key) or self.ctx.platform.platform_key)

    def applicable(self) -> tuple[bool, str]:
        """(True, '') where the add-on's platforms and some release site name this platform, else the reason."""
        ok, reason = super().applicable()
        if ok and not releases.has_asset(self, self.ctx.platform.platform_key):
            return False, f"no prebuilt {self.addon.id} binary is published for this platform ({self.ctx.platform.os}/{self.ctx.platform.arch})"
        return ok, reason

    def installed_version(self) -> str | None:
        """The recorded version while the engine is on disk; else None."""
        recorded = self.recorded("version")
        return str(recorded) if recorded and self.engine.exists() else None

    def fetch_engine(self, version: str, dest: Path) -> None:
        """Download the engine for this version into ``dest``, verified: the source release first, the kit's mirror after it."""
        releases.fetch_binary(self, version, self.ctx.platform.platform_key, dest, what=f"{self.addon.id} {version}",
                              pin_key=self.digest_key(version))

    def launcher_content(self) -> str | None:
        """The launcher script, or None when the add-on has no launcher."""
        if not self.addon.launcher:
            return None
        return f'#!/bin/sh\n# {self.addon.launcher} launcher - generated by the Exasol Personal Local Starter Kit.\nexec "{self.engine}" "$@"\n'

    def write_launchers(self) -> None:
        """Write the launcher into the bin dir."""
        content = self.launcher_content()
        if content and self.addon.launcher:
            self.write_launcher(self.addon.launcher, content)

    def install(self, version: str) -> None:
        """Download the engine, write the launcher, run what follows, record the version."""
        ok, reason = self.applicable()
        if not ok:
            raise Failed(reason)
        force = self.ctx.env.get("EXAKIT_FORCE_COMPONENT_INSTALL") == "1"
        if self.installed_version() == version and not force:
            self.ctx.ui.ok(f"{self.addon.id} {version} is already installed")
            return
        self.ctx.ui.info(f"Installing {self.addon.id} {version} (prebuilt)")
        with temp_dir(f"exakit-{self.addon.id}-") as tmp:
            staged = Path(tmp) / "engine"
            self.fetch_engine(version, staged)
            self.engine.parent.mkdir(parents=True, exist_ok=True)
            staged.replace(self.engine)
        make_executable(self.engine)
        if not self.ctx.runner.run([str(self.engine), "--help"], timeout=30).ok:
            raise Failed(f"the prebuilt {self.addon.id} does not run on this machine (see log)")
        self.after_engine(version)
        self.write_launchers()
        self.record(version=version, engine=str(self.engine), command=str(self.ctx.paths.bin_dir / self.addon.launcher) if self.addon.launcher else None)
        self.ctx.ui.ok(f"{self.addon.id} {version} installed")

    def after_engine(self, version: str) -> None:
        """What follows the engine download; nothing by default."""
        return

    def repair(self) -> None:
        """Rewrite the launcher."""
        self.write_launchers()

    def uninstall(self, *, dry_run: bool) -> list[str]:
        """Remove the folder and the launcher; subclasses add their own cleanup."""
        removed = self.remove_paths([self.home] + ([self.ctx.paths.bin_dir / self.addon.launcher] if self.addon.launcher else []), dry_run=dry_run)
        if not dry_run:
            self.forget()
            self.ctx.ui.ok(f"{self.addon.id} removed - reinstall any time with: exakit marketplace")
        return removed
