"""A Python tool in its own venv: ``uv venv`` + ``uv pip install``, a launcher in the bin dir.

The install spec comes from the catalog source: a PyPI package pinned to the
version, a GitHub tag tarball, or a verified wheel from a release.
"""

from __future__ import annotations

from pathlib import Path

from exakit.adapters.uv import package_version
from exakit.domain.errors import Failed

from .base import LifecycleBase


class PythonVenvLifecycle(LifecycleBase):
    seed = True

    @property
    def venv(self) -> Path:
        """The add-on's venv under the kit home."""
        return self.ctx.paths.home / f"{self.addon.id}-venv"

    @property
    def python(self) -> Path:
        """The venv's interpreter by layout alone, so presence checks never need uv."""
        return self.venv / ("Scripts/python.exe" if self.ctx.platform.os == "windows" else "bin/python")

    @property
    def package(self) -> str:
        """The package to install, from the catalog."""
        return self.addon.source.get("package") or self.addon.id

    def package_version(self) -> str | None:
        """The installed package's version, or None."""
        return package_version(self.python, self.package, self.ctx.runner) if self.python.exists() else None

    def installed_version(self) -> str | None:
        """The recorded version while the venv or the launcher is still on disk (the cheap probe every status uses)."""
        recorded = self.recorded("version")
        if not recorded:
            return None
        launcher = self.ctx.paths.bin_dir / self.addon.launcher if self.addon.launcher else None
        if self.python.exists() or (launcher is not None and launcher.exists()):
            return str(recorded)
        return None

    def install_spec(self, version: str) -> str:
        """What pip installs for a version: a pin, a tag tarball or a wheel."""
        source = self.addon.source
        if source["type"] == "pypi":
            return f"{self.package}=={version.lstrip('v')}"
        if source["type"] == "github_tag":
            return f"https://github.com/{source['repo']}/archive/refs/tags/v{version.lstrip('v')}.tar.gz"
        raise Failed(f"{self.addon.id}: source type {source['type']} needs its own lifecycle module")

    def ensure_venv(self) -> None:
        """Create the venv when it does not exist."""
        if not self.python.exists():
            self.uv().venv(self.venv, seed=self.seed)

    def install_package(self, version: str) -> None:
        """Install the package at the version into the venv."""
        self.ensure_venv()
        self.uv().pip_install(self.python, self.install_spec(version))
        if not self.package_version():
            raise Failed(f"{self.package} did not install into {self.venv}")

    def launcher_content(self) -> str | None:
        """A shell wrapper around the venv's console script; subclasses add environment."""
        if not self.addon.launcher:
            return None
        script = self.uv().bin_of(self.venv, self.addon.launcher)
        return f'#!/bin/sh\n# {self.addon.launcher} launcher - generated by the Exasol Personal Local Starter Kit.\nexec "{script}" "$@"\n'

    def write_launchers(self) -> None:
        """Write the launcher into the bin dir, when the add-on has one."""
        content = self.launcher_content()
        if content and self.addon.launcher:
            self.write_launcher(self.addon.launcher, content)

    def install(self, version: str) -> None:
        """Install the package, write the launchers, record the version."""
        force = self.ctx.env.get("EXAKIT_FORCE_COMPONENT_INSTALL") == "1"
        if self.package_version() == version.lstrip("v") and not force:
            self.ctx.ui.ok(f"{self.addon.id} {version} already installed: {self.venv}")
        else:
            self.ctx.ui.info(f"Installing {self.addon.id} {version}")
            self.install_package(version)
            self.ctx.ui.ok(f"{self.addon.id} installed: {self.venv}")
        self.write_launchers()
        self.record(version=version, venv=str(self.venv), python=str(self.python),
                    command=str(self.ctx.paths.bin_dir / self.addon.launcher) if self.addon.launcher else None)

    def repair(self) -> None:
        """Rewrite the launchers."""
        self.write_launchers()

    def uninstall(self, *, dry_run: bool) -> list[str]:
        """Remove the venv and the launcher."""
        removed = self.remove_paths([self.venv] + ([self.ctx.paths.bin_dir / self.addon.launcher] if self.addon.launcher else []), dry_run=dry_run)
        if not dry_run:
            self.forget()
            self.ctx.ui.ok(f"{self.addon.id} removed - reinstall any time with: exakit marketplace")
        return removed
