"""What the app sees of a runtime: the status record and the protocol every runtime adapter implements."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True, slots=True)
class RuntimeStatus:
    state: str            # running | stopped | starting | conflict | interrupted | not deployed | not installed
    port: int
    detail: str = ""


class PersonalRuntime(Protocol):
    def status(self) -> RuntimeStatus: ...
    def running(self) -> bool: ...
    def deployment_exists(self) -> bool: ...
    def start(self, say: Callable[[str], None]) -> None: ...
    def stop(self, say: Callable[[str], None]) -> None: ...
    def wait_ready(self, say: Callable[[str], None], *, budget: int | None = None) -> bool: ...
    def deploy(self, say: Callable[[str], None]) -> None: ...
    def db_port(self) -> int: ...
    def wedged(self) -> str | None: ...
    def reap_orphan(self, port: int, say: Callable[[str], None]) -> bool: ...
    def cli(self) -> str: ...
    def destroy(self) -> bool: ...
    def deployed_version(self) -> str | None: ...
    def deploy_again(self) -> bool: ...
    def install_local(self) -> tuple[bool, str]: ...
    def recover_slow_first_boot(self, say: Callable[[str], None]) -> bool: ...
    def podman_answers(self) -> tuple[bool, str]: ...
    def launcher_state(self) -> str: ...
    def launcher_version(self) -> str | None: ...
    def tls_answers(self, port: int | None = None) -> bool: ...
