"""dash-server: the AI dashboard host. A venv from the release tarball, a port, a launcher, a service."""

from __future__ import annotations

import tarfile
from pathlib import Path

from exakit.adapters.process.ports import port_holders, port_in_use
from exakit.adapters.process.services import ServiceSpec
from exakit.adapters.net.http import http_status
from exakit.domain.errors import Failed
from exakit.lifecycles.base import ServiceHooks, temp_dir, wait_for
from exakit.lifecycles.python_venv import PythonVenvLifecycle
import contextlib


LAUNCHER = """#!/bin/sh
# dash-server launcher - generated by the Exasol Personal Local Starter Kit.
# Runs the kit's dash-server against the local database; regenerated by: exakit update dash-server
_ds_default_port={port}
_ds_port=""; _ds_seen=""
for _ds_arg in "$@"; do
    if [ "$_ds_seen" = "port" ]; then _ds_port="$_ds_arg"; _ds_seen=""; continue; fi
    case "$_ds_arg" in --port) _ds_seen="port" ;; --port=*) _ds_port="${{_ds_arg#--port=}}" ;; esac
done
case "$_ds_port" in ''|*[!0-9]*) _ds_port="$_ds_default_port" ;; esac
if command -v curl >/dev/null 2>&1 && curl -s -o /dev/null --max-time 2 "http://127.0.0.1:$_ds_port/mcp"; then
    printf 'dash-server is already running: http://127.0.0.1:%s (MCP: /mcp)\\n' "$_ds_port"
    printf 'State: exakit status   Logs: exakit logs dash-server -f   Stop: exakit stop\\n'
    exit 0
fi
: "${{DASH_SERVER_INSTANCE_PATH:={instance}}}"; export DASH_SERVER_INSTANCE_PATH
if [ -n "{dsn}" ] && [ -z "${{DASH_SERVER_EXASOL_DSN:-}}" ]; then
    if [ -z "${{EXA_PASSWORD:-}}" ] && [ -r "{pwfile}" ]; then EXA_PASSWORD="$(cat "{pwfile}")"; export EXA_PASSWORD; fi
    if [ -n "${{EXA_PASSWORD:-}}" ]; then
        export DASH_SERVER_EXASOL_PROFILE_NAME="starter-kit"
        export DASH_SERVER_EXASOL_DSN="{dsn}"
        export DASH_SERVER_EXASOL_USER="{user}"
        export DASH_SERVER_EXASOL_SECRET_ENV_VAR="EXA_PASSWORD"
        export DASH_SERVER_EXASOL_TLS_VERIFY="${{DASH_SERVER_EXASOL_TLS_VERIFY:-false}}"
    fi
fi
: "${{DASH_SERVER_HOST:=127.0.0.1}}"
: "${{DASH_SERVER_PORT:=$_ds_port}}"
export DASH_SERVER_HOST DASH_SERVER_PORT
exec "{venv_bin}" "$@"
"""


class Lifecycle(PythonVenvLifecycle):
    @property
    def home(self) -> Path:
        """The add-on's folder under the kit home."""
        return self.ctx.paths.home / "dash-server"

    @property
    def instance(self) -> Path:
        """Where dashboards are stored."""
        return self.home / "instance"

    @property
    def pidfile(self) -> Path:
        """The server's pid file."""
        return self.home / "dash-server.pid"

    @property
    def log_file(self) -> Path:
        """The server's log under the kit's logs."""
        return self.ctx.paths.logs / "dash-server.log"

    @property
    def launcher(self) -> Path:
        """The launcher in the bin dir."""
        return self.ctx.paths.bin_dir / "dash-server"

    # --- port ----------------------------------------------------------------------

    def port(self) -> int:
        """The port: EXAKIT_DASH_SERVER_PORT, else the recorded one, else the catalog's service port."""
        explicit = self.ctx.env.get("EXAKIT_DASH_SERVER_PORT", "")
        if explicit.isdigit():
            return int(explicit)
        recorded = self.recorded("port")
        return int(recorded) if isinstance(recorded, int) or (isinstance(recorded, str) and recorded.isdigit()) else int((self.addon.service or {}).get("port") or 0)

    def foreign_holder(self, port: int) -> str | None:
        """The description of a process holding the port that is not our venv, else None."""
        if not port_in_use(port):
            return None
        holders = port_holders(port, self.ctx.runner)
        if not holders:
            return None if self.http_answers(port) else "unknown process"
        for holder in holders:
            if str(self.venv) in holder.command:
                return None
        return holders[0].description

    def settle_port(self) -> int:
        """A free port at or past the configured one; a port held by something else is walked past or refused."""
        port = self.port()
        holder = self.foreign_holder(port)
        if holder is None:
            return port
        if self.ctx.env.get("EXAKIT_DASH_SERVER_PORT", "").isdigit():
            raise Failed(f"port {port} is held by another process ({holder}) - pick a free one with EXAKIT_DASH_SERVER_PORT=<port>")
        for candidate in range(port + 1, port + 21):
            if self.foreign_holder(candidate) is None and not port_in_use(candidate):
                self.ctx.ui.warn(f"Port {port} is held by another process ({holder})")
                self.ctx.ui.info(f"dash-server will use port {candidate} instead (recorded, so every command agrees).")
                return candidate
        raise Failed(f"no free port found between {port} and {port + 20} - free one, or name one with EXAKIT_DASH_SERVER_PORT=<port>")

    def http_answers(self, port: int, path: str = "/mcp") -> bool:
        """Something HTTP answers on the port (any status below 500 counts: the server is up)."""
        status = http_status(f"http://127.0.0.1:{port}{path}", timeout=5)
        return status is not None and status < 500

    # --- install -----------------------------------------------------------------------

    def restore_package_data(self, version: str) -> None:
        """The release tarball's non-.py files that pip leaves out (templates), copied in when missing."""
        source = self.addon.source
        url = self.ctx.catalog.kit.endpoints.url("archive_tag", repo=source["repo"], ref=f"v{version.lstrip('v')}")
        site = self.ctx.runner.run([str(self.python), "-c", "import dash_server, os; print(os.path.dirname(dash_server.__file__))"], timeout=30)
        if not site.ok or not site.out.strip():
            return
        target = Path(site.out.strip())
        with temp_dir("exakit-dash-") as tmp:
            archive = Path(tmp) / "src.tar.gz"
            try:
                self.ctx.net.fetch(url, archive, what="dash-server sources")
                with tarfile.open(archive) as tar:
                    tar.extractall(tmp, filter="data")
            except Exception as err:
                self.ctx.log.line("WARN", f"dash-server package data not restored: {err}")
                return
            copied = 0
            for src_dir in Path(tmp).glob("*/src/dash_server"):
                for file in src_dir.rglob("*"):
                    if file.is_file() and file.suffix != ".py":
                        dest = target / file.relative_to(src_dir)
                        if not dest.exists():
                            dest.parent.mkdir(parents=True, exist_ok=True)
                            dest.write_bytes(file.read_bytes())
                            copied += 1
            if copied:
                self.ctx.ui.info(f"Restored {copied} data file(s) the package left out")

    def launcher_content(self) -> str | None:
        """The launcher script, or None before the runtime credentials exist."""
        dsn, user, pw_file = self.runtime_credentials()
        manifest = self.ctx.manifest_or_none()
        ro_user = manifest.get("components.mcp_server.connection.user") if manifest else None
        ro_file = manifest.get("components.mcp_server.connection.password_file") if manifest else None
        if ro_user and ro_file:
            user, pw_file = ro_user, ro_file
        return LAUNCHER.format(port=self.port(), instance=self.instance, dsn=dsn, pwfile=pw_file or "", user=user,
                               venv_bin=self.uv().bin_of(self.venv, "dash-server"))

    def install(self, version: str) -> None:
        """Install the package into its venv, write the launcher, start the server and validate it."""
        port = self.settle_port()
        force = self.ctx.env.get("EXAKIT_FORCE_COMPONENT_INSTALL") == "1"
        if self.package_version() == version.lstrip("v") and not force:
            self.ctx.ui.ok(f"dash-server {version} already installed: {self.venv}")
        else:
            self.ctx.ui.info(f"Installing dash-server {version}")
            self.install_package(version)
            self.restore_package_data(version)
            self.ctx.ui.ok(f"dash-server installed: {self.venv}")
        self.instance.mkdir(parents=True, exist_ok=True)
        self.record(port=port)
        self.write_launchers()
        self.record(version=version, venv=str(self.venv), python=str(self.python), command=str(self.launcher), port=port,
                    instance=str(self.instance))
        from exakit.app import mcp
        try:
            mcp.register_addon_servers(self.ctx, "dash-server")
        except Exception as err:
            self.ctx.log.line("WARN", f"dash-server MCP registration: {err}")

    # --- validate and service ----------------------------------------------------------

    def validate(self) -> None:
        """The server imports and answers over HTTP; records validated and ui_validated."""
        if not self.python.exists():
            return
        if not self.ctx.runner.run([str(self.python), "-c", "import dash_server"], timeout=60).ok:
            self.ctx.ui.warn("dash-server did not import from its environment - repair with: exakit update dash-server")
            self.record(validated=False)
            return
        port = self.port()
        holder = self.foreign_holder(port)
        if holder:
            self.ctx.ui.warn(f"Port {port} is held by another process ({holder})")
            self.ctx.ui.info("Move it with: EXAKIT_DASH_SERVER_PORT=<port> exakit update")
            self.record(validated=False)
            return
        if self.http_answers(port):
            self.ctx.ui.ok(f"dash-server control plane answers on http://127.0.0.1:{port}")
            self.record(validated=True, ui_validated=self.http_answers(port, "/"))
            return
        self.start()
        if self.http_answers(port):
            self.record(validated=True, ui_validated=self.http_answers(port, "/"))
        else:
            self.record(validated=False)

    def status(self) -> str:
        """running, stopped, or not installed."""
        if not self.launcher.exists():
            return "not installed"
        port = self.port()
        if self.http_answers(port) and self.foreign_holder(port) is None:
            return "running"
        holder = self.foreign_holder(port)
        return f"stopped (port {port} is held by another process: {holder})" if holder else "stopped"

    def start(self) -> None:
        """Start the server as a daemon and wait for it to answer."""
        if not self.launcher.exists():
            self.ctx.ui.warn("dash-server is not installed - add it with: exakit marketplace")
            raise Failed("dash-server is not installed", remedy="exakit marketplace dash-server")
        port = self.port()
        if self.http_answers(port) and self.foreign_holder(port) is None:
            self.ctx.ui.ok(f"dash-server is already running (http://127.0.0.1:{port})")
            return
        holder = self.foreign_holder(port)
        if holder:
            self.ctx.ui.warn(f"Port {port} is held by another process ({holder}), so dash-server cannot start. Move it with: EXAKIT_DASH_SERVER_PORT=<port> exakit update")
            raise Failed(f"port {port} is held by another process", remedy="exakit start")
        pid = self.ctx.runner.spawn([str(self.launcher), "--host", "127.0.0.1", "--port", str(port)], log_path=self.log_file)
        self.home.mkdir(parents=True, exist_ok=True)
        self.pidfile.write_text(str(pid))
        if wait_for(lambda: self.http_answers(port), seconds=60):
            self.record(port=port)
            self.ctx.ui.ok(f"dash-server is running: http://127.0.0.1:{port} (MCP: /mcp)")
            return
        self.ctx.ui.warn(f"dash-server did not answer on port {port} within 60s - see: exakit logs dash-server")
        raise Failed("dash-server did not start", remedy="exakit logs dash-server")

    def pids(self) -> list[int]:
        """The pids of the kit's running server processes."""
        pids: set[int] = set()
        try:
            pid = int(self.pidfile.read_text().strip())
            if self.ctx.runner.run(["kill", "-0", str(pid)], timeout=5).ok:
                pids.add(pid)
        except (OSError, ValueError):
            pass
        found = self.ctx.runner.run(["pgrep", "-f", str(self.venv)], timeout=10)
        pids.update(int(p) for p in found.out.split() if p.isdigit())
        return sorted(pids)

    def stop(self) -> None:
        """Stop the server by pid."""
        pids = self.pids()
        if not pids and not self.http_answers(self.port()):
            self.ctx.ui.ok("dash-server is already stopped")
            self.pidfile.unlink(missing_ok=True)
            return
        self.ctx.ui.info("Stopping dash-server")
        for pid in pids:
            self.ctx.runner.run(["pkill", "-P", str(pid)], timeout=5)
            self.ctx.runner.run(["kill", str(pid)], timeout=5)
        wait_for(lambda: not self.pids(), seconds=3, every=0.5)
        for pid in self.pids():
            self.ctx.runner.run(["kill", "-9", str(pid)], timeout=5)
        self.pidfile.unlink(missing_ok=True)
        if self.http_answers(self.port()) and self.foreign_holder(self.port()) is None:
            self.ctx.ui.warn("dash-server still answers after being stopped - see: exakit logs dash-server")
            raise Failed("dash-server did not stop")
        self.ctx.ui.ok("dash-server stopped")

    def service(self) -> ServiceHooks:
        """The hooks start, stop and autostart use."""
        return ServiceHooks(status=self.status, start=self.start, stop=self.stop,
                            url=lambda: f"http://127.0.0.1:{self.port()}", log_path=lambda: self.log_file,
                            autostart=lambda: ServiceSpec("dash-server", (str(self.launcher), "--host", "127.0.0.1", "--port", str(self.port()))))

    def summary(self) -> str | None:
        """The closing line with the dashboards URL."""
        return f"dashboards: http://127.0.0.1:{self.port()}"

    # --- update and uninstall ----------------------------------------------------------------

    def repair(self) -> None:
        """Rewrite the launcher."""
        self.write_launchers()

    def uninstall(self, *, dry_run: bool) -> list[str]:
        """Stop the server and remove the venv, the folder and the launcher; dashboards go with the kit home."""
        if not dry_run:
            with contextlib.suppress(Failed):
                self.stop()
        removed = self.remove_paths([self.venv, self.pidfile, self.launcher], dry_run=dry_run)
        if self.instance.exists():
            if self.ctx.env.get("EXAKIT_UNINSTALL_FULL") == "1":
                self.ctx.ui.text(f"  your dashboards in {self.instance} go with the kit home")
            else:
                self.ctx.ui.text(f"  keeping your dashboards: {self.instance} (reinstalling the add-on picks them up again; "
                                 "delete the folder yourself if you no longer want them)")
        elif not dry_run and self.home.exists():
            with contextlib.suppress(OSError):
                self.home.rmdir()
        if not dry_run:
            from exakit.app import mcp
            try:
                mcp.unregister_server_entry(self.ctx, "dash-server", "dash-server")
            except Exception as err:
                self.ctx.log.line("WARN", f"dash-server MCP entry: {err}")
            self.forget()
            self.ctx.ui.ok("dash-server removed - reinstall any time with: exakit marketplace")
        return removed
