"""JSON Tables: a Python package from a verified wheel plus a prebuilt ingest engine, from the add-on's own release (the kit's mirror after it)."""

from __future__ import annotations

import json
import tarfile
from pathlib import Path

from exakit.domain.errors import Failed
from exakit.lifecycles import releases
from exakit.lifecycles.base import make_executable, temp_dir
from exakit.lifecycles.python_venv import PythonVenvLifecycle

SHIM = """#!/bin/sh
# cargo shim - generated by the Exasol Personal Local Starter Kit for JSON Tables.
# The package shells out to `cargo run` for its ingest engine; this answers that one call
# with the prebuilt engine and hands anything else to a real cargo on PATH.
if [ "$1" = "run" ]; then
    _jt_is_ingest=0
    for _jt_arg in "$@"; do case "$_jt_arg" in *json_tables_ingest*) _jt_is_ingest=1 ;; esac; done
    if [ "$_jt_is_ingest" = "1" ]; then
        _jt_seen=0
        for _jt_arg in "$@"; do
            if [ "$_jt_seen" = "1" ]; then set -- "$@" "$_jt_arg"; fi
            [ "$_jt_arg" = "--" ] && _jt_seen=1
            shift
        done
        exec "{engine}" "$@"
    fi
fi
_jt_real=""; _jt_oldifs="$IFS"; IFS=:
for _jt_dir in $PATH; do
    [ "$_jt_dir" = "{shimdir}" ] && continue
    if [ -x "$_jt_dir/cargo" ]; then _jt_real="$_jt_dir/cargo"; break; fi
done
IFS="$_jt_oldifs"
if [ -n "$_jt_real" ]; then exec "$_jt_real" "$@"; fi
printf 'cargo: not installed, and this is not the JSON Tables ingest call the kit can answer.\\n' >&2
exit 127
"""

LAUNCHER = """#!/bin/sh
# exasol-json-tables launcher - generated by the Exasol Personal Local Starter Kit. Regenerated by:
#   exakit update json-tables
PATH="{shimdir}:$PATH"
export PATH
exec "{script}" "$@"
"""


class Lifecycle(PythonVenvLifecycle):
    @property
    def home(self) -> Path:
        """The add-on's folder under the kit home."""
        return self.ctx.paths.home / "json-tables"

    @property
    def engine(self) -> Path:
        """The prebuilt ingest engine."""
        return self.home / "libexec" / "json_to_parquet"

    @property
    def shim_dir(self) -> Path:
        """Where the cargo shim lives."""
        return self.home / "shim"

    @property
    def launcher(self) -> Path:
        """The launcher in the bin dir."""
        return self.ctx.paths.bin_dir / "exasol-json-tables"

    # --- platform and versions ------------------------------------------------------

    def engine_asset(self, version: str) -> str | None:
        """The prebuilt ingest engine for this platform on the first release site that publishes one; None where none does."""
        return releases.asset_for(self, version, self.ctx.platform.platform_key)

    def applicable(self) -> tuple[bool, str]:
        """(True, '') where some release site publishes an engine for this platform, else the reason."""
        if not self.addon.supports(self.ctx.platform.platform_key) or not releases.has_asset(self, self.ctx.platform.platform_key):
            return False, f"no prebuilt ingest engine is published for this platform ({self.ctx.platform.os}/{self.ctx.platform.arch})"
        return True, ""

    def installed_version(self) -> str | None:
        """The recorded version when the venv, the engine and the import all still work; else None."""
        recorded = self.recorded("version")
        if not recorded or not self.python.exists() or not self.engine.exists():
            return None
        if not self.ctx.runner.run([str(self.python), "-c", "import exasol_json_tables"], timeout=60).ok:
            return None
        return str(recorded)

    def system_present(self) -> bool:
        """True when an exasol-json-tables that is not the kit's is on PATH or importable from the ambient Python."""
        found = self.ctx.runner.which("exasol-json-tables")
        if found and Path(found).resolve() != self.launcher.resolve():
            return True
        ambient = self.ctx.runner.which("python3") or self.ctx.runner.which("python")
        if ambient and str(self.venv) not in ambient and str(self.ctx.paths.home) not in ambient:
            return self.ctx.runner.run([ambient, "-c", "import exasol_json_tables"], timeout=30).ok
        return False

    def wheel_name(self, version: str) -> str | None:
        """The wheel's file name: the pin in versions.json, else what the first release site names."""
        return releases.asset_for(self, version, "wheel")

    # --- install ----------------------------------------------------------------------------

    def restore_package_data(self, version: str) -> None:
        """Copy the package's non-Python files from the upstream sources when pip left them out."""
        site = self.ctx.runner.run([str(self.python), "-c", "import exasol_json_tables, os; print(os.path.dirname(exasol_json_tables.__file__))"], timeout=30)
        if not site.ok or not site.out.strip():
            return
        target = Path(site.out.strip())
        with temp_dir("exakit-jt-src-") as tmp:
            archive = Path(tmp) / "src.tar.gz"
            try:
                ref = str(self.addon.source.get("sources", "{version}")).format(version=version)
                self.ctx.net.fetch(self.ctx.catalog.kit.endpoints.url("archive_ref", repo=str(self.addon.source["repo"]), ref=ref), archive,
                                   what="json-tables sources")
                with tarfile.open(archive) as tar:
                    tar.extractall(tmp, filter="data")
            except Exception as err:
                self.ctx.log.line("WARN", f"json-tables package data not restored: {err}")
                return
            for src_dir in Path(tmp).glob("*/python/exasol_json_tables"):
                for file in src_dir.rglob("*"):
                    if file.is_file() and file.suffix != ".py":
                        dest = target / file.relative_to(src_dir)
                        if not dest.exists():
                            dest.parent.mkdir(parents=True, exist_ok=True)
                            dest.write_bytes(file.read_bytes())

    def write_launchers(self) -> None:
        """Write the cargo shim and the launcher that puts it first on PATH."""
        self.shim_dir.mkdir(parents=True, exist_ok=True)
        shim = self.shim_dir / "cargo"
        shim.write_text(SHIM.format(engine=self.engine, shimdir=self.shim_dir), encoding="utf-8")
        make_executable(shim)
        self.write_launcher("exasol-json-tables", LAUNCHER.format(shimdir=self.shim_dir, script=self.uv().bin_of(self.venv, "exasol-json-tables")))

    def install(self, version: str) -> None:
        """Install the wheel into its venv, the engine, the shim and the launcher, and prove the engine runs."""
        ok, reason = self.applicable()
        if not ok:
            raise Failed(reason)
        if not self.wheel_name(version):
            raise Failed("the catalog names no wheel for JSON Tables - update the kit first: exakit update", remedy="exakit update")
        self.ctx.ui.info(f"Installing JSON Tables {version} (prebuilt)")
        self.ensure_venv()
        with temp_dir("exakit-jt-") as tmp:
            wheel = releases.fetch_asset(self, version, "wheel", Path(tmp) / "wheel", what=f"JSON Tables {version} wheel", pin_key="wheel")
            self.uv().pip_install(self.python, str(wheel.path))
            self.restore_package_data(version)
            staged = Path(tmp) / "engine"
            releases.fetch_binary(self, version, self.ctx.platform.platform_key, staged, what=f"JSON Tables {version} engine",
                                  pin_key=self.ctx.platform.platform_key)
            self.engine.parent.mkdir(parents=True, exist_ok=True)
            staged.replace(self.engine)
        make_executable(self.engine)
        if not self.ctx.runner.run([str(self.engine), "--help"], timeout=30).ok:
            raise Failed("the prebuilt ingest engine does not run on this machine (see log)")
        self.write_launchers()
        self.record(version=version, venv=str(self.venv), python=str(self.python), engine=str(self.engine), command=str(self.launcher))
        self.ctx.ui.ok(f"JSON Tables installed: {self.venv}")

    def validate(self) -> None:
        """The package imports and the engine turns a sample JSON into Parquet; records validated."""
        if not self.python.exists():
            return
        if not self.ctx.runner.run([str(self.python), "-c", "import exasol_json_tables"], timeout=60).ok:
            self.ctx.ui.warn("JSON Tables did not import from its environment - repair with: exakit update json-tables")
            self.record(validated=False)
            return
        with temp_dir("exakit-jt-check-") as tmp:
            sample = Path(tmp) / "sample.json"
            sample.write_text(json.dumps([{"id": 1, "name": "alpha"}, {"id": 2, "name": "beta"}]))
            out = Path(tmp) / "out"
            done = self.ctx.runner.run([str(self.engine), "--input", str(sample), "--output-dir", str(out)], timeout=120,
                                       env={"PATH": f"{self.shim_dir}:{self.ctx.env.get('PATH', '')}"})
            parquet = list(out.rglob("*.parquet")) if out.exists() else []
        if done.ok and parquet:
            self.record(validated=True)
            self.ctx.ui.ok("Ingest works: JSON in, Parquet out")
        else:
            self.record(validated=False)
            self.ctx.ui.warn("The JSON Tables engine did not produce Parquet from a sample - see: exakit logs json-tables")

    def summary(self) -> str | None:
        """The closing line naming the ingest command."""
        return "ingest JSON: exasol-json-tables"

    def repair(self) -> None:
        """Rewrite the shim and the launcher."""
        self.write_launchers()

    def uninstall(self, *, dry_run: bool) -> list[str]:
        """Remove the venv, the folder and the launcher."""
        removed = self.remove_paths([self.venv, self.home, self.launcher], dry_run=dry_run)
        if not dry_run:
            self.forget()
            self.ctx.ui.ok("JSON Tables removed - reinstall any time with: exakit marketplace")
        return removed
